// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04r04Z5sRf8RvvjKSi7tQC85p4qdkQEQ',
    appId: '1:792623897496:web:8b4e95ca4e5ea7ab4aa9ed',
    messagingSenderId: '792623897496',
    projectId: 'guptabhelpuri-8be2d',
    authDomain: 'guptabhelpuri-8be2d.firebaseapp.com',
    storageBucket: 'guptabhelpuri-8be2d.firebasestorage.app',
    measurementId: 'G-X89ZS64739',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifom8eeJnJvhKwKaKaV_qxmbNb9YUuHM',
    appId: '1:792623897496:android:7b7661798af57b464aa9ed',
    messagingSenderId: '792623897496',
    projectId: 'guptabhelpuri-8be2d',
    storageBucket: 'guptabhelpuri-8be2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEMNMAa1P_FiMVcnFdxCZEfIa7VrZV1E8',
    appId: '1:792623897496:ios:27d977668e7ea6754aa9ed',
    messagingSenderId: '792623897496',
    projectId: 'guptabhelpuri-8be2d',
    storageBucket: 'guptabhelpuri-8be2d.firebasestorage.app',
    iosClientId: '792623897496-jempt2gc7rgkvahqfotj6p55t2jtutoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.guptabhelpuri',
  );
}
